### ISSUE TITLE
Separate tasks as individual commands for concreate

### ISSUE THREAD

**Issue by rcernich** [jboss-container-images/concreate#28]
Currently, the only command supported is "build" which also cleans the target area before generating the Dockerfile.  I propose adding the following commands:

* clean - clean the target/output directory
* generate - generate the Dockerfile, copying over all the artifacts, modules, etc., allowing the user to manually invoke ``docker build ...``
* build - does what it does today?

As part of this, it may make sense to default --target to image.yaml/../target, while also defaulting the file to build to image.yaml, allowing for something like: ``concreate build`` which tries to build the image.yaml located in the cwd, placing all the generated content in ./target/.

One reason for separating the generate and build steps is that it gives the developer the ability to specify alternate tags, e.g. robtest/eap64-openshift:CLOUD-1234.  It might also be worthwhile to have a --tag option so you could do something like: concreate build --tag=robtest/eap64-openshift:CLOUD-1234

This seems like it could be broken out into two or three issues, so feel free to split it apart as you see fit.

**Comment by dbecvarik** [comment]
We planed something like this. @goldmann can probably link his suggestion here.

We wanted to encapsulate test subcommand as is in condev now.

**Comment by goldmann** [comment]
Indeed, this was generally speaking the idea.

The "clean" target is now hidden and I would probably left it that way. Since target directory can be redefined at execution time we don't have the control over what to clean. Thus - we should clean (always) when we start to generate/build.

The "generate" target you're mentioning is also hidden currently. We were thinking that user is more interested in image itself compared to image sources, but I'm happy to add it back. I have done a PoC locally and it works nicely together with the "build" target. I'll link it in a second.

We do plan to include other targets like; "test" or "release". First one is obvious. The "release" target would generate and execute a build in the build system.

Default target and `image.yaml` locations will be fixed in my PoC with one note - `--target` will be default to 'target' in current working directory.

Regarding the tag - I created #33.

**Comment by goldmann** [comment]
And here is the PoC: https://github.com/jboss-container-images/concreate/pull/34

**Comment by goldmann** [comment]
Since this is touching CLI and there is a proposal already there I'm scheduling this for `1.0`.

**Comment by rcernich** [comment]
That all sounds good.  I don't think clean is necessarily a requirement for generate/build, although generate is certainly a requirement for build.  I may be coming at this from too much of a ``make`` perspective (``concreate clean generate build``), as opposed to a ``maven`` perspective where the prerequisites are implied (``mvn install``).

That said, I'm lobbying for a discrete ``generate`` option, simply for debugging the generation piece.  Also, some teams may have different release processes, which may require this.  (I think one team is committing the generated Dockerfile to a repo as part of their build process.  I don't know if that happens before or after ``docker build``.)

**Comment by dbecvarik** [comment]
I +1 for @rcernich solution here.

**Comment by goldmann** [comment]
IMHO the clean target is required for generate. The reason is that if we commit generated sources to some repository as part of the process, we could accidentally commit some left overs. And to be exact: clean does not remove the whole target directory, but removed only required things like modules. We generally don't remove the whole dir because we have there saved (cached) artifact, which may be big and slow to download. We leave removal of this directory to the user.

The generate target was added to my PoC, as I mentioned before.

So what's the suggestion here? @dbecvarik mentioned to remove subparsers. Is it the only change to my proposal?

**Comment by dbecvarik** [comment]
I think for now the biggest issue is that clean operation is probably unclear. We have little bit different workflow and target directory handling in concreate than we had with dogen/condev.

Concreate works that it treats target directory as a kind of workspace. The important tree for building image/committing Dockerfiles is `target/image`  where Dockerfile and required modules are stored. 
We also fetch artifacts here. In ideal world we should wipe `target/image` for every generate command - but with our current approach we will loose our artifacts.

Then what clean should do? It should probably remove whole target directory and next generate will download everything fresh. 
Maybe we should download artifacts to target/artifacts and copy them to image when they/re needed? Than we can wipe whole `target/image` directory every generate command, and if we run clean command, we will just wipe whole `target` ?
With placing artifacts like this we are much safer with working with `target/image` consistently for modules and artifacts.

**Comment by goldmann** [comment]
This is exactly why I would to postpone exposing the `clean` target entirely for now. Let's focus on `generate` and `build` for `1.0` and later we will think about exposing cleaning functionality.

**Comment by dbecvarik** [comment]
+1, we can emulate it by rm -rf /target for now. Maybe refactor method from clean to something like `prepare_image_dir` so its easier to guess what it does in the code.

**Comment by goldmann** [comment]
PoC updated: https://github.com/jboss-container-images/concreate/pull/34#issuecomment-328821414

**Comment by goldmann** [comment]
So, since #34 was merged, I'm going to close this ticket. We can open new issues about specific things to improve.
